name: ai_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.2
  flutter_svg: ^0.21.0+1
  intl: ^0.17.0
  google_maps_flutter: ^2.0.6
  english_words: ^3.1.5
  geolocator: ^7.0.3
  circular_profile_avatar: ^2.0.0
  velocity_x: ^3.0.0
  audioplayers: ^0.18.3
  bubbled_navigation_bar: ^0.0.3
  flutter_localizations:
    sdk: flutter

  animator: ^3.0.0
  otp_text_field: ^1.1.1
  flutter_local_notifications: ^5.0.0

  percent_indicator: ^3.0.1
  camera: ^0.8.1+3
  cached_network_image: ^3.1.0
  flutter_cached_pdfview: 0.4.0-nullsafety
  timeline_tile: ^2.0.0
  google_fonts: ^2.0.0
  table_calendar: ^3.0.0
  numberpicker: ^2.1.1
  fl_chart: ^0.36.1
  local_auth: ^1.1.6

  flutter_bloc: ^7.1.0
  json_annotation: 3.1.1
  image_picker: ^0.7.5+3
  flutter_exif_rotation: ^0.4.1

  shared_preferences: ^2.0.6
  shared_preferences_web: ^2.0.0

  minimize_app: ^0.1.1
  firebase_messaging: ^10.0.4
  firebase_core: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_animations: ^1.3.3
  build_runner:
  json_serializable: 3.5.1

dependency_overrides:
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    -  "assets/images/home/"
    -  "assets/images/background/"
    -  "assets/images/objects/"
    -  "assets/images/cards/"
    -  "assets/images/weather/"
    -  "assets/images/avatar/"
    -  "assets/images/message/"
    -  "assets/images/landing/"
    -  "assets/images/queue/"
    -  "assets/images/landing/sample/"
    -  "assets/images/report/"
    -  "assets/images/profile/"
    -  "assets/images/auth/"
    -  "assets/images/rainfall/"
    -  "assets/images/ccs/"
    -  "assets/images/contractor/"
    -  "assets/images/activity/"
    -  "assets/images/station/"
    -  "assets/images/notification/"
    -  "lib/bloc/plot_state/demo.json"
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DB Heavent
      fonts:
        - asset: assets/fonts/DB-Heavent-Li-Cond.ttf
        - asset: assets/fonts/DB-Heavent-Li-Cond-It.ttf
          style: italic
        - asset: assets/fonts/DB-Heavent-Cond.ttf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages